name: Build and Release Nginx RPM

on:
  push:
    paths:
      - "nginx-source/**"
      - "rpmbuild/SPECS/nginx.spec"
      - ".github/workflows/build-nginx-release.yml"

jobs:
  build-nginx-release:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: .

      - name: Install build dependencies
        run: |
          dnf install -y epel-release
          dnf config-manager --set-enabled crb
          dnf groupinstall -y "Development Tools"
          dnf install -y gcc gcc-c++ make autoconf automake libtool \
            pcre pcre-devel zlib zlib-devel openssl openssl-devel \
            libaio-devel libatomic libatomic_ops-devel \
            libmaxminddb libmaxminddb-devel \
            gperftools gperftools-devel \
            luajit luajit-devel \
            perl-devel perl-ExtUtils-Embed \
            wget unzip git which \
            perl readline-devel systemd-devel

      - name: Prepare rpmbuild directories
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cp rpmbuild/SOURCES/nginx.service ~/rpmbuild/SOURCES/
          cp rpmbuild/SPECS/nginx.spec ~/rpmbuild/SPECS/
          cd ~/rpmbuild/SOURCES/
          wget https://nginx.org/download/nginx-1.25.0.tar.gz

      - name: Build RPM
        run: rpmbuild -ba ~/rpmbuild/SPECS/nginx.spec

      - name: Find built RPM
        id: find_rpm
        run: |
          RPM_PATH=$(find ~/rpmbuild/RPMS/ -name "nginx-*.rpm" | head -n1)
          echo "rpm_path=$RPM_PATH" >> $GITHUB_OUTPUT
      
      - name: Generate changelog from Git commits
        run: |
          git log -n 20 --pretty=format:"- %s (%h)" > changelog.txt

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_rpm.outputs.rpm_path }}
          body_path: changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
