name: Build and Release Nginx RPM

on:
  push:
    paths:
      - 'nginx-source/**'
      - '.github/workflows/build-and-release.yml'
      - 'scripts/**'
      - 'rpmbuild/SPECS/nginx.spec'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up RPM build environment and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm rpm2cpio cpio gcc make wget \
            libpcre3-dev zlib1g-dev libssl-dev libreadline-dev \
            libluajit-5.1-dev libsystemd-dev autoconf automake libtool git

      - name: Prepare rpmbuild directories
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cp -r ./rpmbuild/SOURCES/* ~/rpmbuild/SOURCES/
          cp ./rpmbuild/SPECS/nginx.spec ~/rpmbuild/SPECS/

      - name: Copy nginx source tarball
        run: |
          cp ./nginx-source/nginx-*.tar.gz ~/rpmbuild/SOURCES/

      - name: Build RPM
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/nginx.spec

      - name: Find built RPM
        id: find_rpm
        run: |
          RPM_PATH=$(find ~/rpmbuild/RPMS/ -name "nginx-*.rpm" | head -n1)
          echo "rpm_path=$RPM_PATH" >> $GITHUB_OUTPUT

      - name: Generate changelog
        run: |
          ./scripts/generate_changelog.sh > changelog.txt

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_rpm.outputs.rpm_path }}
          body_path: changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}