name: Build and Release Nginx RPM

on:
  push:
    paths:
      - 'nginx-source/**'
      - 'rpmbuild/SPECS/nginx.spec'
      - 'scripts/**'
      - '.github/workflows/build-and-release.yml'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          dnf install -y epel-release
          dnf groupinstall -y "Development Tools"
          dnf install -y rpm-build wget git autoconf automake libtool \
            pcre-devel openssl-devel zlib-devel systemd-devel \
            readline-devel perl luajit luajit-devel which

      - name: Prepare rpmbuild directories
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

          # Copy nginx source tarball (still from repo)
          cp ./nginx-source/nginx-1.25.0.tar.gz ~/rpmbuild/SOURCES/

          # Copy service file
          cp ./rpmbuild/SOURCES/nginx.service ~/rpmbuild/SOURCES/

          # Download remaining source files from GitHub
          cd ~/rpmbuild/SOURCES/

          curl -L -O https://github.com/leev/ngx_http_geoip2_module/archive/refs/tags/v3.4.tar.gz 
          curl -L -O https://github.com/vozlt/nginx-module-vts/archive/refs/tags/v0.2.4.tar.gz 
          curl -L -O https://github.com/vision5/ngx_devel_kit/archive/refs/tags/v0.3.4.tar.gz 
          curl -L -O https://github.com/openresty/lua-nginx-module/archive/refs/tags/v0.10.28.tar.gz 
          curl -L -O https://github.com/openresty/lua-resty-core/archive/refs/tags/v0.1.31.tar.gz 
          curl -L -O https://github.com/openresty/lua-resty-lrucache/archive/refs/tags/v0.15.tar.gz 

          # Rename files to match what's expected in the .spec
          mv v3.4.tar.gz ngx_http_geoip2_module-v3.4.tar.gz
          mv v0.2.4.tar.gz nginx-module-vts-v0.2.4.tar.gz
          mv v0.3.4.tar.gz ngx_devel_kit-v0.3.4.tar.gz
          mv v0.10.28.tar.gz lua-nginx-module-v0.10.28.tar.gz
          mv v0.1.31.tar.gz lua-resty-core-v0.1.31.tar.gz
          mv v0.15.tar.gz lua-resty-lrucache-v0.15.tar.gz

          # Copy nginx.spec
          cp ./rpmbuild/SPECS/nginx.spec ~/rpmbuild/SPECS/

      - name: Build RPM
        run: rpmbuild -ba ~/rpmbuild/SPECS/nginx.spec

      - name: Find built RPM
        id: find_rpm
        run: |
          RPM_PATH=$(find ~/rpmbuild/RPMS/ -name "nginx-*.rpm" | head -n1)
          echo "rpm_path=$RPM_PATH" >> $GITHUB_OUTPUT

      - name: Generate changelog
        run: ./scripts/generate_changelog.sh > changelog.txt

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_rpm.outputs.rpm_path }}
          body_path: changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
