name: Build and Release Tengine RPM

on:
  push:
    paths:
      - "nginx-source/**"
      - "rpmbuild/SPECS/tengine.spec"
      - ".github/workflows/build-tengine-release.yml"

jobs:
  build-tengine-release:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          dnf install -y epel-release
          dnf install -y \
            rpm-build \
            wget \
            git \
            autoconf \
            automake \
            libtool \
            pcre-devel \
            zlib-devel \
            openssl-devel \
            systemd-devel \
            readline-devel \
            perl \
            luajit \
            luajit-devel \
            which \
            gcc \
            make \
            libmaxminddb-devel

      - name: Prepare rpmbuild directories
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cp ./rpmbuild/SOURCES/nginx.service ~/rpmbuild/SOURCES/
          cp ./rpmbuild/SPECS/tengine.spec ~/rpmbuild/SPECS/
          cd ~/rpmbuild/SOURCES/ 
          wget https://tengine.taobao.org/download/tengine-3.1.0.tar.gz
         
          
      - name: Build RPM
        run: rpmbuild -ba ~/rpmbuild/SPECS/tengine.spec

      - name: Find built RPM
        id: find_rpm
        run: |
          RPM_PATH=$(find ~/rpmbuild/RPMS/ -name "nginx-*.rpm" | head -n1)
          echo "rpm_path=$RPM_PATH" >> $GITHUB_OUTPUT

      - name: Generate changelog
        run: ./scripts/generate_changelog.sh > changelog.txt

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_rpm.outputs.rpm_path }}
          body_path: changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
