name: Build and Release Nginx RPM

on:
  push:
    paths:
      - 'nginx-source/**'
      - 'rpmbuild/SPECS/nginx.spec'
      - 'scripts/**'
      - '.github/workflows/build-and-release.yml'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    container:
      image: quay.io/centos/centos:stream9

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          dnf install -y epel-release
          dnf groupinstall -y "Development Tools"
          dnf install -y rpm-build wget git autoconf automake libtool \
            pcre-devel openssl-devel zlib-devel systemd-devel \
            readline-devel perl luajit luajit-devel which

      - name: Prepare rpmbuild directories
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cp -r ./rpmbuild/SOURCES/* ~/rpmbuild/SOURCES/
          cp ./rpmbuild/SPECS/nginx.spec ~/rpmbuild/SPECS/

      - name: Copy nginx source tarball
        run: cp ./nginx-source/nginx-1.25.0.tar.gz ~/rpmbuild/SOURCES/

      - name: Build RPM
        run: rpmbuild -ba ~/rpmbuild/SPECS/nginx.spec

      - name: Find built RPM
        id: find_rpm
        run: |
          RPM_PATH=$(find ~/rpmbuild/RPMS/ -name "nginx-*.rpm" | head -n1)
          echo "rpm_path=$RPM_PATH" >> $GITHUB_OUTPUT

      - name: Generate changelog
        run: ./scripts/generate_changelog.sh > changelog.txt

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_rpm.outputs.rpm_path }}
          body_path: changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
